server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/
spring:
  application:
    name: hello-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  zipkin:
    base-url: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh