server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/
spring:
  application:
    name: ribbon-consumer