server:
  port: 8769
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JohnsonEEE/spring-cloud-action.git
          search-paths: spring-cloud-action/config-repo
          username: 278013157@qq.com
          password: yiyijohnson11