server:
  port: 7001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JohnsonEEE/spring-cloud-action.git
          search-paths: config-repo
          username: 278013157@qq.com
          password: yiyijohnson11