server:
  port: 7001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JohnsonEEE/spring-cloud-action.git
          search-paths: config-repo
          username: 278013157@qq.com
          password: yiyijohnson11
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/