server:
  port: 8768

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/
spring:
  application:
    name: hystrix-consumer
  zipkin:
    base-url: http://localhost:9411/